# Generated by Django 4.2.5 on 2023-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rapport_date_saisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
