# Generated by Django 4.2.5 on 2023-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_rapport_date_saisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date_saisie',
            field=models.DateTimeField(null=True),
        ),
    ]
