# Generated by Django 4.2.5 on 2023-10-20 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_rapport_date_saisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_activite_phisique',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form_activite_phisique',
            name='duree_activite_physique',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='duree_total_douleurs_thoracique',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='duree_total_malaises',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='duree_total_palpitations',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='heure_debut_douleurs_thoracique',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='heure_debut_malaises',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='form_autres_symptomes',
            name='heure_debut_palpitations',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='form_info_cardiaque_tension_arterielle',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form_prise_medoc',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
